import numpy as np
import pandas as pd
from collections import Counter
from random import shuffle
from time import sleep
import cv2

FILE_NAME = "data.npy" # This is the default file name when capturing training data
#FILE_NAME = "balancedData.npy" # This file is automatically generated when training, note: images are randomized!

data = np.load(FILE_NAME, allow_pickle=True)

for frame in data:
    screenShot = frame[0]
    direction = frame[1]
    screenShot = cv2.resize(screenShot, (960, 540))
    cv2.imshow("frame", screenShot)
    print(direction)
    #this snippet taken from https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html
    if cv2.waitKey(1) and 0xFF == ord('q'):
        break
